- type: roleLoadout
  id: JobPsychologist
  groups:
  - GroupTankHarness
  # Common groups
  # - PsychologistHead
  - PsychologistGlasses
  # - PsychologistMask
  - PsychologistNeck
  # - PsychologistGloves
  - PsychologistJumpsuit
  - PsychologistBackpack
  # - PsychologistPDA
  # - PsychologistBelt
  # - PsychologistOuterClothing
  - PsychologistShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - PsychologistSpecial
  - PsychologistTrinkets
  - PsychologistPets
