- type: roleLoadout
  id: JobAtmosphericTechnician
  groups:
  - GroupTankHarness
  # Common groups
  # - AtmosphericTechnicianHead
  - AtmosphericTechnicianGlasses
  # - AtmosphericTechnicianMask
  - AtmosphericTechnicianNeck
  # - AtmosphericTechnicianGloves
  - AtmosphericTechnicianJumpsuit
  - AtmosphericTechnicianBackpack
  # - AtmosphericTechnicianPDA
  # - AtmosphericTechnicianBelt
  - AtmosphericTechnicianOuterClothing
  - AtmosphericTechnicianShoes
  # Backpack fills
  - SurvivalExtended
  - GroupSpeciesBreathTool
  # - AtmosphericTechnicianSpecial
  - AtmosphericTechnicianTrinkets
  - AtmosphericTechnicianPets
