- type: roleLoadout
  id: JobResearchAssistant
  groups:
  - GroupTankHarness
  # Common groups
  # - ResearchAssistantHead
  - ResearchAssistantGlasses
  # - ResearchAssistantMask
  - ResearchAssistantNeck
  # - ResearchAssistantGloves
  - ResearchAssistantJumpsuit
  - ResearchAssistantBackpack
  # - ResearchAssistantPDA
  # - ResearchAssistantBelt
  # - ResearchAssistantOuterClothing
  - ResearchAssistantShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - ResearchAssistantSpecial
  - ResearchAssistantTrinkets
  - ResearchAssistantPets
