- type: roleLoadout
  id: JobScientist
  groups:
  - GroupTankHarness
  # Common groups
  - ScientistHead
  - ScientistGlasses
  # - ScientistMask
  - ScientistNeck
  - ScientistGloves
  - ScientistJumpsuit
  - ScientistBackpack
  - ScientistPDA
  # - ScientistBelt
  - ScientistOuterClothing
  - ScientistShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - ScientistSpecial
  - ScientistTrinkets
  - ScientistPets
