- type: roleLoadout
  id: JobBoxer
  groups:
  - GroupTankHarness
  # Common groups
  # - BoxerHead
  - BoxerGlasses
  # - BoxerMask
  - BoxerNeck
  - BoxerGloves
  - BoxerJumpsuit
  - BoxerBackpack
  # - BoxerPDA
  # - BoxerBelt
  # - BoxerOuterClothing
  - BoxerShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - BoxerSpecial
  - BoxerTrinkets
  - BoxerPets
