- type: roleLoadout
  id: JobChaplain
  canCustomizeName: true
  groups:
  - GroupTankHarness
  # Common groups
  - ChaplainHead
  - ChaplainGlasses
  - ChaplainMask
  - ChaplainNeck
  # - ChaplainGloves
  - ChaplainJumpsuit
  - ChaplainBackpack
  # - ChaplainPDA
  # - ChaplainBelt
  - ChaplainOuterClothing
  - ChaplainShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  - ChaplainSpecial
  - ChaplainTrinkets
  - ChaplainPets
