- type: roleLoadout
  id: JobChef
  groups:
  - GroupTankHarness
  # Common groups
  - ChefHead
  - ChefGlasses
  - ChefMask
  - ChefNeck
  # - ChefGloves
  - ChefJumpsuit
  - ChefBackpack
  # - ChefPDA
  # - ChefBelt
  - ChefOuterClothing
  - ChefShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - ChefSpecial
  - ChefTrinkets
  - ChefPets
