- type: roleLoadout
  id: JobClown
  canCustomizeName: true
  groups:
  - GroupTankHarness
  # Common groups
  - ClownHead
  - ClownGlasses
  # - ClownMask
  - ClownNeck
  # - ClownGloves
  - ClownJumpsuit
  - ClownBackpack
  # - ClownPDA
  # - ClownBelt
  - ClownOuterClothing
  - ClownShoes
  # Backpack fills
  - SurvivalClown
  # - GroupSpeciesBreathTool
  # - ClownSpecial
  - ClownTrinkets
  - ClownPets
