- type: roleLoadout
  id: JobLibrarian
  groups:
  - GroupTankHarness
  # Common groups
  # - LibrarianHead
  - LibrarianGlasses
  # - LibrarianMask
  - LibrarianNeck
  # - LibrarianGloves
  - LibrarianJumpsuit
  - LibrarianBackpack
  # - LibrarianPDA
  # - LibrarianBelt
  # - LibrarianOuterClothing
  - LibrarianShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - LibrarianSpecial
  - LibrarianTrinkets
  - LibrarianPets
