- type: roleLoadout
  id: JobMime
  canCustomizeName: true
  groups:
  - GroupTankHarness
  # Common groups
  - MimeHead
  - MimeGlasses
  - MimeMask
  - MimeNeck
  # - MimeGloves
  - MimeJumpsuit
  - MimeBackpack
  # - MimePDA
  - MimeBelt
  - MimeOuterClothing
  - MimeShoes
  # Backpack fills
  - SurvivalMime
  # - GroupSpeciesBreathTool
  # - MimeSpecial
  - MimeTrinkets
  - MimePets
