- type: roleLoadout
  id: JobPassenger
  groups:
  - GroupTankHarness
  # Common groups
  # - PassengerHead
  - PassengerGlasses
  - PassengerMask
  - PassengerNeck
  - PassengerGloves
  - PassengerJumpsuit
  - PassengerBackpack
  # - PassengerPDA
  # - PassengerBelt
  - PassengerOuterClothing
  - PassengerShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - PassengerSpecial
  - PassengerTrinkets
  - PassengerPets
