- type: roleLoadout
  id: JobZookeeper
  groups:
  - GroupTankHarness
  # Common groups
  # - ZookeeperHead
  - ZookeeperGlasses
  # - ZookeeperMask
  - ZookeeperNeck
  # - ZookeeperGloves
  # - ZookeeperJumpsuit
  - ZookeeperBackpack
  # - ZookeeperPDA
  # - ZookeeperBelt
  # - ZookeeperOuterClothing
  - ZookeeperShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - ZookeeperSpecial
  - ZookeeperTrinkets
  - ZookeeperPets
