- type: roleLoadout
  id: JobSecurityCadet
  groups:
  # - GroupTankHarness
  # Common groups
  # - SecurityCadetHead
  - SecurityCadetGlasses
  # - SecurityCadetMask
  - SecurityCadetNeck
  # - SecurityCadetGloves
  - SecurityCadetJumpsuit
  - SecurityCadetBackpack
  # - SecurityCadetPDA
  # - SecurityCadetBelt
  # - SecurityCadetOuterClothing
  - SecurityCadetShoes
  # Backpack fills
  - SurvivalSecurity
  - GroupSpeciesBreathToolSecurity
  # - SecurityCadetSpecial
  - SecurityCadetTrinkets
  - SecurityCadetPets
