- type: roleLoadout
  id: JobSecurityOfficer
  groups:
  # - GroupTankHarness
  # Common groups
  - SecurityOfficerHead
  - SecurityOfficerGlasses
  # - SecurityOfficerMask
  - SecurityOfficerNeck
  # - SecurityOfficerGloves
  - SecurityOfficerJumpsuit
  - SecurityOfficerBackpack
  - SecurityOfficerPDA
  - SecurityOfficerBelt
  - SecurityOfficerOuterClothing
  - SecurityOfficerShoes
  # Backpack fills
  - SurvivalSecurity
  - GroupSpeciesBreathToolSecurity
  # - SecurityOfficerSpecial
  - SecurityOfficerTrinkets
  - SecurityOfficerPets
