- type: roleLoadout
  id: JobWarden
  groups:
  # - GroupTankHarness
  # Common groups
  - WardenHead
  - WardenGlasses
  # - WardenMask
  - WardenNeck
  # - WardenGloves
  - WardenJumpsuit
  - WardenBackpack
  # - WardenPDA
  - WardenBelt
  - WardenOuterClothing
  - WardenShoes
  # Backpack fills
  - SurvivalSecurity
  - GroupSpeciesBreathToolSecurity
  # - WardenSpecial
  - WardenTrinkets
  - WardenPets
