- type: roleLoadout
  id: JobCaptain
  groups:
  # - GroupTankHarness
  # Common groups
  - CaptainHead
  - CaptainGlasses
  # - CaptainMask
  - CaptainNeck
  # - CaptainGloves
  - CaptainJumpsuit
  - CaptainBackpack
  # - CaptainPDA
  # - CaptainBelt
  - CaptainOuterClothing
  - CaptainShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - CaptainSpecial
  - CaptainTrinkets
  - CaptainPets
