- type: roleLoadout
  id: JobChiefMedicalOfficer
  groups:
  - GroupTankHarness
  # Common groups
  - ChiefMedicalOfficerHead
  - ChiefMedicalOfficerGlasses
  - ChiefMedicalOfficerMask
  - ChiefMedicalOfficerNeck
  - ChiefMedicalOfficerGloves
  - ChiefMedicalOfficerJumpsuit
  - ChiefMedicalOfficerBackpack
  # - ChiefMedicalOfficerPDA
  # - ChiefMedicalOfficerBelt
  - ChiefMedicalOfficerOuterClothing
  - ChiefMedicalOfficerShoes
  # Backpack fills
  - SurvivalMedical
  - GroupSpeciesBreathToolMedical
  # - ChiefMedicalOfficerSpecial
  - ChiefMedicalOfficerTrinkets
  - ChiefMedicalOfficerPets
