- type: roleLoadout
  id: JobHeadOfPersonnel
  groups:
  - GroupTankHarness
  # Common groups
  - HeadOfPersonnelHead
  - HeadOfPersonnelGlasses
  # - HeadOfPersonnelMask
  - HeadOfPersonnelNeck
  # - HeadOfPersonnelGloves
  - HeadOfPersonnelJumpsuit
  - HeadOfPersonnelBackpack
  # - HeadOfPersonnelPDA
  # - HeadOfPersonnelBelt
  - HeadOfPersonnelOuterClothing
  - HeadOfPersonnelShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - HeadOfPersonnelSpecial
  - HeadOfPersonnelTrinkets
  - HeadOfPersonnelPets
