- type: roleLoadout
  id: JobResearchDirector
  groups:
  - GroupTankHarness
  # Common groups
  - ResearchDirectorHead
  - ResearchDirectorGlasses
  # - ResearchDirectorMask
  - ResearchDirectorNeck
  - ResearchDirectorGloves
  - ResearchDirectorJumpsuit
  - ResearchDirectorBackpack
  # - ResearchDirectorPDA
  # - ResearchDirectorBelt
  - ResearchDirectorOuterClothing
  - ResearchDirectorShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - ResearchDirectorSpecial
  - ResearchDirectorTrinkets
  - ResearchDirectorPets
