- type: roleLoadout
  id: JobSalvageSpecialist
  groups:
  - GroupTankHarness
  # Common groups
  # - SalvageSpecialistHead
  - SalvageSpecialistGlasses
  # - SalvageSpecialistMask
  - SalvageSpecialistNeck
  # - SalvageSpecialistGloves
  # - SalvageSpecialistJumpsuit
  - SalvageSpecialistBackpack
  # - SalvageSpecialistPDA
  # - SalvageSpecialistBelt
  - SalvageSpecialistOuterClothing
  - SalvageSpecialistShoes
  # Backpack fills
  - Survival
  - GroupSpeciesBreathTool
  # - SalvageSpecialistSpecial
  - SalvageSpecialistTrinkets
  - SalvageSpecialistPets
